server:
  port: 10300
spring:
  application:
    name: kof
  datasource:
    username: root
    password: hmsz741679
    url: jdbc:mysql://localhost:3306/kob?useUnicode=true&characterEncoding=utf-8&&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

